[environments.default]
url = "jdbc:sqlserver://localhost;databasename=FlywayDemo;encrypt=false"
schema = "dbo"
user = "flyway_user"
password = "StrongPassword!"

[flyway]
locations = ["filesystem:dbo.sql/migrations", "classpath:db/migrations"]